"use strict";
const PREVIOUS_BOOTSTRAP="https://cdn.jsdelivr.net/gh/tiagosilvagba/Almoxarifado@bb6ede30b8e351bf50734aa84a3ed28e12b5bb1c/script.js";
const PREVIOUS_BOOTSTRAP_FALLBACK="https://raw.githubusercontent.com/tiagosilvagba/Almoxarifado/bb6ede30b8e351bf50734aa84a3ed28e12b5bb1c/script.js";
const RESPONSIVE_LAYOUT_MODULE="./responsive-layout.js?v=20260914-2";
const GITHUB_COMMIT_QUEUE_MODULE="./github-commit-queue.js?v=20260914-1";
const PAGE_SNAPSHOT_PDF_MODULE="./page-snapshot-pdf.js?v=20260914-1";
const SALDO_UPDATE_TIME_MODULE="./saldo-update-time.js?v=20260914-1";
const COMPARATIVO_META_MODULE="./comparativo-meta.js?v=20260914-1";
const LAYOUT_FIX_MODULE="./layout-fix.js?v=20260914-3";
const COMPARATIVO_PERIODOS_MODULE="./comparativo-periodos.js?v=20260914-1";
const COMPARATIVO_EXCEL_MODULE="./comparativo-excel-padrao.js?v=20260914-3";
const COMPARATIVO_ITEM_SPLIT_MODULE="./comparativo-item-split.js?v=20260914-2";
const COMPARATIVO_META_VISUAL_MODULE="./comparativo-meta-visual.js?v=20260914-2";
const COMPARATIVO_INCLUSOES_MODULE="./comparativo-inclusoes.js?v=20260914-2";
const COMPARATIVO_INCLUSOES_BASE_MODULE="./comparativo-inclusoes-base.js?v=20260914-1";
const COMPARATIVO_CARDS_RESUMO_MODULE="./comparativo-cards-resumo.js?v=20260914-2";
const COMPARATIVO_MES_A_MES_MODULE="./comparativo-mes-a-mes.js?v=20260914-6";
const COMPARATIVO_ESCALA_MIL_MODULE="./comparativo-escala-mil.js?v=20260914-2";
const AREA_FILTER_ACTIVE_MODULE="./area-filter-active.js?v=20260914-1";
const GITHUB_PHOTO_UPLOAD_MODULE="./github-photo-upload-v2.js?v=20260914-1";
const CURRENT_PUBLIC_VERSION="Versão 4.9";
(function installRepositoryFallback(){if(window.__almoxRepositoryFallbackInstalled)return;window.__almoxRepositoryFallbackInstalled=true;const nativeFetch=window.fetch.bind(window),apiPattern=/^https:\/\/api\.github\.com\/repos\/tiagosilvagba\/Almoxarifado\/contents(?:\?ref=main)?$/i,months=["Jan","Fev","Mar","Abr","Mai","Jun","Jul","Ago","Set","Out","Nov","Dez"];async function fileExists(name){const url=`./${encodeURIComponent(name).replace(/%2F/gi,"/")}`;try{const h=await nativeFetch(url,{method:"HEAD",cache:"no-store"});if(h.ok)return true;if(![405,501].includes(h.status))return false}catch{}try{const g=await nativeFetch(url,{method:"GET",cache:"no-store",headers:{Range:"bytes=0-0"}});return g.ok||g.status===206}catch{return false}}async function discover(){const c=["00 - Saldo_Online.csv","01 - Compras_Almox.csv","02 - Responsaveis_Reposição.CSV","03 - Consumo.csv"];for(let p=1;p<=20;p++)c.push(`01 - Compras_Almox_Parte_${String(p).padStart(2,"0")}.CSV`);const y=new Date().getFullYear();for(let yr=y-3;yr<=y+1;yr++)for(const m of months)c.push(`01 - Estoque_${m}_${yr}.csv`);const u=[...new Set(c)],f=[];for(let i=0;i<u.length;i+=8){const r=await Promise.all(u.slice(i,i+8).map(async name=>({name,exists:await fileExists(name)})));for(const x of r)if(x.exists)f.push({name:x.name,path:x.name,type:"file",sha:"same-origin-discovery"})}return f}window.fetch=async function(input,init){const url=typeof input==="string"?input:input?.url||"";if(!apiPattern.test(url))return nativeFetch(input,init);try{const r=await nativeFetch(input,init);if(r.ok)return r}catch{}return new Response(JSON.stringify(await discover()),{status:200,headers:{"Content-Type":"application/json; charset=utf-8","X-Almoxarifado-Fallback":"same-origin-full-data-discovery"}})}})();
function loadIncrementalScript(src){return new Promise((resolve,reject)=>{const s=document.createElement("script");s.src=src;s.async=false;s.onload=resolve;s.onerror=reject;document.head.appendChild(s)})}
function enforceCurrentPublicVersion(){const b=document.getElementById("versionBadge");if(b)b.textContent=CURRENT_PUBLIC_VERSION;document.documentElement.dataset.appVersion=CURRENT_PUBLIC_VERSION.replace(/^Versão\s*/i,"")}
(async function(){try{await loadIncrementalScript(RESPONSIVE_LAYOUT_MODULE)}catch{}try{await loadIncrementalScript(GITHUB_COMMIT_QUEUE_MODULE)}catch{}try{await loadIncrementalScript(PREVIOUS_BOOTSTRAP)}catch{await loadIncrementalScript(PREVIOUS_BOOTSTRAP_FALLBACK)}enforceCurrentPublicVersion();for(const [src,msg] of [[SALDO_UPDATE_TIME_MODULE,"horário oficial da atualização do Saldo Online"],[PAGE_SNAPSHOT_PDF_MODULE,"PDF visual da página atual"],[AREA_FILTER_ACTIVE_MODULE,"filtro ativo por área"],[GITHUB_PHOTO_UPLOAD_MODULE,"fila imutável de fotos por item"],[COMPARATIVO_META_MODULE,"mês meta e filtros dinâmicos"],[LAYOUT_FIX_MODULE,"correção estrutural do layout"],[COMPARATIVO_PERIODOS_MODULE,"rótulos de período do comparativo"],[COMPARATIVO_EXCEL_MODULE,"exportação Excel padronizada"],[COMPARATIVO_ITEM_SPLIT_MODULE,"separação de código e nome do item"],[COMPARATIVO_META_VISUAL_MODULE,"cálculo visual comparado x mês meta"],[COMPARATIVO_INCLUSOES_MODULE,"inclusões e reduções de estoque zeradas"],[COMPARATIVO_INCLUSOES_BASE_MODULE,"inclusões calculadas contra o mês base"],[COMPARATIVO_CARDS_RESUMO_MODULE,"cards Top 10 revisados do comparativo"],[COMPARATIVO_MES_A_MES_MODULE,"cards Meta e Meta linear vs mês comparado"],[COMPARATIVO_ESCALA_MIL_MODULE,"escala x1000 de saldo e consumo"]]){try{await loadIncrementalScript(src)}catch(e){console.error(`Não foi possível carregar ${msg}.`,e)}}enforceCurrentPublicVersion();[250,800,1800].forEach(d=>setTimeout(enforceCurrentPublicVersion,d))})();